# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1411, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 20, 381, 151))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(510, 20, 241, 151))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.pushButton__GentrySag = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__GentrySag.setGeometry(QtCore.QRect(60, 200, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton__GentrySag.setFont(font)
        self.pushButton__GentrySag.setObjectName("pushButton__GentrySag")
        self.pushButton__EpidSag = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__EpidSag.setGeometry(QtCore.QRect(340, 200, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton__EpidSag.setFont(font)
        self.pushButton__EpidSag.setObjectName("pushButton__EpidSag")
        self.pushButton__IzoSize = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__IzoSize.setGeometry(QtCore.QRect(40, 310, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton__IzoSize.setFont(font)
        self.pushButton__IzoSize.setObjectName("pushButton__IzoSize")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(490, 410, 291, 271))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 40, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_CouchZize = QtWidgets.QLabel(self.groupBox)
        self.label_CouchZize.setGeometry(QtCore.QRect(50, 130, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_CouchZize.setFont(font)
        self.label_CouchZize.setObjectName("label_CouchZize")
        self.label_CouchZize_2 = QtWidgets.QLabel(self.groupBox)
        self.label_CouchZize_2.setGeometry(QtCore.QRect(220, 130, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_CouchZize_2.setFont(font)
        self.label_CouchZize_2.setObjectName("label_CouchZize_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(420, 80, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 400, 321, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_CouchZize_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_CouchZize_3.setGeometry(QtCore.QRect(230, 130, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_CouchZize_3.setFont(font)
        self.label_CouchZize_3.setObjectName("label_CouchZize_3")
        self.label_GentrySize = QtWidgets.QLabel(self.groupBox_2)
        self.label_GentrySize.setGeometry(QtCore.QRect(70, 120, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_GentrySize.setFont(font)
        self.label_GentrySize.setObjectName("label_GentrySize")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(930, 400, 321, 261))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_GentryIZOSIZE = QtWidgets.QLabel(self.groupBox_3)
        self.label_GentryIZOSIZE.setGeometry(QtCore.QRect(50, 110, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_GentryIZOSIZE.setFont(font)
        self.label_GentryIZOSIZE.setObjectName("label_GentryIZOSIZE")
        self.label_CouchZize_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_CouchZize_5.setGeometry(QtCore.QRect(240, 110, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_CouchZize_5.setFont(font)
        self.label_CouchZize_5.setObjectName("label_CouchZize_5")
        self.pushButton__ConeIzoSize = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__ConeIzoSize.setGeometry(QtCore.QRect(960, 260, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton__ConeIzoSize.setFont(font)
        self.pushButton__ConeIzoSize.setObjectName("pushButton__ConeIzoSize")
        self.pushButton__Summary = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__Summary.setGeometry(QtCore.QRect(330, 290, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton__Summary.setFont(font)
        self.pushButton__Summary.setObjectName("pushButton__Summary")
        self.pushButton__SummaryCone = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__SummaryCone.setGeometry(QtCore.QRect(920, 150, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton__SummaryCone.setFont(font)
        self.pushButton__SummaryCone.setObjectName("pushButton__SummaryCone")
        self.pushButton__ConeOpen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton__ConeOpen.setGeometry(QtCore.QRect(900, 30, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton__ConeOpen.setFont(font)
        self.pushButton__ConeOpen.setObjectName("pushButton__ConeOpen")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.slot1)
        self.spinBox.valueChanged['QString'].connect(MainWindow.changeImages)
        self.pushButton__GentrySag.clicked.connect(MainWindow.GentrySag)
        self.pushButton__EpidSag.clicked.connect(MainWindow.getEpidSag)
        self.pushButton__IzoSize.clicked.connect(MainWindow.getIzoSize)
        self.pushButton__ConeIzoSize.clicked.connect(MainWindow.GetConeIzoSize)
        self.pushButton__Summary.clicked.connect(MainWindow.sumary_Info)
        self.pushButton__SummaryCone.clicked.connect(MainWindow.summeryCone)
        self.pushButton__ConeOpen.clicked.connect(MainWindow.OpenCOne)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form1"))
        self.pushButton.setText(_translate("MainWindow", "Open_MLC_Only"))
        self.pushButton__GentrySag.setText(_translate("MainWindow", "Gentri sag"))
        self.pushButton__EpidSag.setText(_translate("MainWindow", "Epid Sag"))
        self.pushButton__IzoSize.setText(_translate("MainWindow", "IzoSize"))
        self.groupBox.setTitle(_translate("MainWindow", "Couch"))
        self.label.setText(_translate("MainWindow", "Couch izo size"))
        self.label_CouchZize.setText(_translate("MainWindow", "Couch izo size"))
        self.label_CouchZize_2.setText(_translate("MainWindow", "mm"))
        self.label_4.setText(_translate("MainWindow", "Couch izo size"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Colimator"))
        self.label_CouchZize_3.setText(_translate("MainWindow", "mm"))
        self.label_GentrySize.setText(_translate("MainWindow", "Gentry izo Size"))
        self.label_2.setText(_translate("MainWindow", "Colimator izo size"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gentry"))
        self.label_3.setText(_translate("MainWindow", "Gentry IZO Size"))
        self.label_GentryIZOSIZE.setText(_translate("MainWindow", "Couch izo size"))
        self.label_CouchZize_5.setText(_translate("MainWindow", "mm"))
        self.pushButton__ConeIzoSize.setText(_translate("MainWindow", "ConeIzoSize"))
        self.pushButton__Summary.setText(_translate("MainWindow", "Summary_MLC"))
        self.pushButton__SummaryCone.setText(_translate("MainWindow", "ConeSummery"))
        self.pushButton__ConeOpen.setText(_translate("MainWindow", "Open_Cone_Only"))

